# Project: xjoi
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main9293.o
LINKOBJ  = main9293.o
LIBS     = -L"D:/Program/Dev-Cpp/MinGW64/lib" -L"D:/Program/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Program/Dev-Cpp/MinGW64/include" -I"D:/Program/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Program/Dev-Cpp/MinGW64/include" -I"D:/Program/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Program/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = xjoi.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main9293.o: main9293.cpp
	$(CPP) -c main9293.cpp -o main9293.o $(CXXFLAGS)
